import { MenuHeader } from '@/components';
import { AuthProvider } from '@/providers';
import { CssBaseline } from '@mui/material';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

const RootLayout = async ({ children }: Props) => {
  return (
    <html lang="pl">
      <body>
        <AuthProvider>
          <CssBaseline />
          <MenuHeader />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
